getmetowork/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'getmetowork.views.home', name='home'),

    url(r'^routeapp/', include('route.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

route/urls.py
__author__ = 'ben'
from django.conf.urls import patterns,  url
from views import RouteCreateView, RouteGroupListView, RouteUpdateView

urlpatterns = patterns('',
    url(r'^update/(?P<pk>\d+)/', RouteUpdateView.as_view(), name='update_route'),
    url(r'^create', RouteCreateView.as_view(), name='create_route'),
    url(r'^$', RouteGroupListView.as_view(), name='list_routes'),
)

route/models.py
from xml.parsers.expat import ExpatError

import gpxpy
from django.db import models
from django.conf import settings


from api_callers.googlemaps import directions_map_url, postcode_from_lat_long
from api_callers.googlemaps import OverQueryLimit
from api_callers.tfl_tims import get_tims_accidents_ll, get_tims_traffic_ll

import decimal

def twodp(num):
    return decimal.Decimal(str(num)).quantize(decimal.Decimal('0.00'))



class RouteGroup(models.Model):
    created = models.DateTimeField(auto_now_add=True,)
    edited = models.DateTimeField(auto_now=True,)
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    embarkation = models.CharField(max_length=255, null = True, blank=True)
    destination = models.CharField(max_length=255, null = True, blank=True)



    def __str__(self):
        if self.embarkation and self.destination:
            return self.embarkation.capitalize() + ' > ' + self.destination.capitalize()
        return self.title

    class Meta:
        ordering = ['-created']


class Route(models.Model):
    route_group = models.ForeignKey(RouteGroup)
    created = models.DateTimeField(auto_now_add=True,)
    edited = models.DateTimeField(auto_now=True,)
    title = models.CharField(max_length=255)
    slug = models.SlugField()
    description = models.CharField(max_length=10000, null = True, blank=True)
    route_gpx_xml = models.TextField()


    def check_gpx(self):
        try:
            return self.get_gpx()
        except (gpxpy.gpx.GPXXMLSyntaxException, ExpatError) as e:
            return False

    #TODO cached_property please
    def get_gpx(self):
        if not hasattr(self, 'gpx'):
            self.gpx = gpxpy.parse(self.route_gpx_xml)
        return self.gpx

    def get_gpx_points(self):
        gpx = self.get_gpx()
        points = [[str(i[0].latitude), str(i[0].longitude)] for i in gpx.walk()]
        return [(float(i[0]),float(i[1])) for i in points]


    #TODO datetime me please
    def get_time_kmh(self):
        return twodp((self.length/1000)/settings.ROUTE_CONTSTANT_SPEED)

    def get_time(self):
        #TODO default get_time
        #Have user option for kmh/ mph and pick method to calc time based on that
        #Do that logic here
        return self.get_time_kmh()

    #TODO cached_property
    @property
    def length(self):
        gpx = self.get_gpx()
        return gpx.length_3d()

    def points_vs_trouble(self, points, coords):
        for point in points:
            for trouble in coords:
                if trouble[1][0]< point[1] < trouble[0][0] and \
                        trouble[0][1]< point[0] < trouble[1][1]:
                    return True
        return False

    def get_incident(self):
        points=self.get_gpx_points()
        incident_coords = get_tims_accidents_ll()
        return self.points_vs_trouble(self, points, incident_coords)

    def get_traffic(self):
        points=self.get_gpx_points()
        traffic_coords = get_tims_traffic_ll()
        return self.points_vs_trouble(self, points, traffic_coords)


    def get_map(self):
        gpx = self.get_gpx()
        points = [[str(i[0].latitude), str(i[0].longitude)] for i in gpx.walk()]
        return directions_map_url(points)


    class Meta:
        ordering = ['-created']

    def __str__(self):
        return self.title

route/forms.py
from django import forms
from models import Route, RouteGroup


class RouteForm(forms.ModelForm):

    class Meta:
        model = Route
        fields = ['route_group', 'title', 'description', 'route_gpx_xml']


class RouteGroupForm(forms.ModelForm):

    class Meta:
        model = RouteGroup

route/views.py
__author__ = 'ben'
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.core.urlresolvers import reverse


from models import Route, RouteGroup
from forms import RouteForm


class RouteCreateView(CreateView):
    
    template_name = 'route/route_create.html'
    # queryset = Post.objects.all()
    form_class = RouteForm
    model = Route

    # def dispatch(self, request, *args, **kwargs):
    #     return super(self.__class__, self).dispatch(request, *args, **kwargs)

    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     form.instance.save()
    #     return super(PostCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('list_routes')



class RouteGroupListView(ListView):
    model = RouteGroup


class RouteUpdateView(UpdateView):

    template_name = 'route/route_create.html'
    # queryset = Post.objects.all()
    form_class = RouteForm
    model = Route

    # def dispatch(self, request, *args, **kwargs):
    #     return super(self.__class__, self).dispatch(request, *args, **kwargs)

    # def form_valid(self, form):
    #     form.instance.user = self.request.user
    #     form.instance.save()
    #     return super(PostCreateView, self).form_valid(form)

    def get_success_url(self):
        return reverse('list_routes')

route/templates/route/includes/base_form.html
{% load bootstrap3 %}


<form action="" method="post" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button type="submit" class="btn btn-primary">
      Submit
    </button>
  {% endbuttons %}
</form>

route/templates/route/route_base.html
{% extends "base.html" %}

    {% block body %}
        {{ block.super }}
        <div class="col-md-2"></div>
        <div class="col-md-8">
        {% block content %}


        {% endblock content %}
        </div>
        <div class="col-md-2"></div>
    {% endblock body %}

route/templates/route/route_create.html
{% extends "route/route_base.html" %}
{% block title %}{{ block.super }} - Create a post{% endblock title %}

{% block content %}


    <h4>Create a new route</h4>
    {% include 'route/includes/base_form.html' %}

{% endblock content %}

route/templates/route/route_update.html
{% extends "route/route_base.html" %}
{% block title %}{{ block.super }} - Create a post{% endblock title %}

{% block content %}


    <h4>Create a new route</h4>
    {% include 'route/includes/base_form.html' %}

{% endblock content %}

route/templates/route/routegroup_list.html
{% extends "route/route_base.html" %}
{% block title %}{{ block.super }} - All{% endblock title %}
{% block content %}
    <h2>Welcome to Get Me To Work (without being run over)</h2>
{% for object in object_list %}
{% comment %}
    <h3><a href="{% url "detail_post" object.slug %}">{{ object.title|capfirst }}</a></h3>
    <h5>by {{ object.user.email }}, {{ object.created|date:'DATETIME_FORMAT' }}</h5><br>
{% endcomment %}

    <h3>{{ object }}</h3>


    <div class="table-responsive">
    <table class="table">
        <tr>
            <th>Route</th><th>Current time</th><th style="text-align:center">Incident</th><th style="text-align:center">Traffic</th><th>Map</th><th style="text-align:center">Parser</th>
        </tr>
        {% for route in object.route_set.all %}
        <tr>
            {% if route.check_gpx %}
                <td><a href="{% url "update_route" pk=route.id %}">{{ route }}</a></td>
                <td>{{ route.get_time }}</td>
                <td>{% if route.get_incident %}<span style="display:block; text-align:center; vertical-align:middle; color: darkgreen" class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>{% else %}<span style="display:block; text-align:center; vertical-align:middle; color: darkred" class="glyphicon-align-center text-center center glyphicon glyphicon-remove-sign" aria-hidden="true"></span>{% endif %}</td>
                <td>{% if route.get_traffic %}<span style="display:block; text-align:center; vertical-align:middle; color: darkgreen" class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span>{% else %}<span style="display:block; text-align:center; vertical-align:middle; color: darkred" class="glyphicon-align-center text-center center glyphicon glyphicon-remove-sign" aria-hidden="true"></span>{% endif %}</td>
                <td><a href="{{ route.get_map }}">Map</a></td>
                <td><span style="display:block; text-align:center; vertical-align:middle; color: darkgreen" class="glyphicon glyphicon-ok-sign" aria-hidden="true"></span></td>
                <td></td>
            {% else %}
                <td><a href="{% url "update_route" pk=route.id %}">{{ route }}</a></td>
                <td></td>
                <td><span style="display:block; text-align:center; vertical-align:middle; color: darkred" class="glyphicon-align-center text-center center glyphicon glyphicon-remove-sign" aria-hidden="true"></span></td>
                <td><span style="display:block; text-align:center; vertical-align:middle; color: darkred" class="glyphicon-align-center text-center center glyphicon glyphicon-remove-sign" aria-hidden="true"></span></td>
                <td></td>
                <td><span style="display:block; text-align:center; vertical-align:middle; color: darkred" class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span></td>
            {% endif  %}
        </tr>
        {% endfor %}
    </table>
    </div>




{% endfor %}

{% if not object_list  %}
    <h3>There are no routes so far!</h3>
{% endif %}

{% endblock content %}

templates/base.html
{% load bootstrap3 %}
{% load static %}
{% load staticfiles %}
<!DOCTYPE html>
<html>
<script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
{# Load CSS and JavaScript #}
{% bootstrap_css %}
{% bootstrap_javascript %}

{# Display django.contrib.messages as Bootstrap alerts #}
{% bootstrap_messages %}

<head>
{% block head %}


<link rel="shortcut icon" type="image/png" href="{% static "favicon.png" %}"/>
<title>{% block title %}Get Me To Work (without being run over){% endblock title %}</title>

{% endblock head %}
</head>


<body>
{% block body %}

<nav class="navbar navbar-inverse" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Get Me To Work</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav navbar-right">
          <p class="navbar-text">
              {# Username, login logout #}
              <span class="welcome">
{% comment %}                  <!--Welcome, {{ user.email }}-->
                  <!--{% if user.email %}-->
                       <!--| <a href="{% url 'logout' %}" class="navbar-link">Logout</a>-->
                  <!--{% else %}-->
                      <!--You're not yet logged in | <a href="{% url 'login' %}" class="navbar-link">Log in</a>-->
                  <!--{% endif %}-->

{% endcomment %}
                  Oh Hai!
              </span>

          <li><a href="{% url 'list_routes' %}">All Routes</a></li>
          <li><a href="{% url 'create_route' %}">New Route</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

{% endblock body %}
</body>